# Test meshpy.
meshpy-testing:
    script:
        - "whoami"
        - "pwd"
        - export PYTHONPATH="${PYTHONPATH}:$(pwd)"
        # Compile cython code.
        - "cd meshpy"
        - "python3 find_close_nodes_setup.py"
        - "cd .."
        # Run tests.
        - "cd tests"
        - "python3 testing_main.py"
    variables:
        # Indicated the testing script, that it is performed on GitLab. In this
        # case all test have to pass.
        TESTING_GITLAB: 1
        BACI_RELEASE: "/hdd/gitlab-runner/lib/baci-master/release/baci-release"
    tags:
        - "imcs-all"
