# Test meshpy.
meshpy-testing:
    script:
        - "pwd"
        - export PYTHONPATH="${PYTHONPATH}:$(pwd)"
        # Compile cython code.
        - "cd meshpy"
        - "python3 find_close_nodes_setup.py"
        - "cd .."
        # Run tests.
        - "cd tests"
        - "python3 testing.py"
    tags:
        - "imcs-all"
